name: production
url: https://harmonia.jules.com

protection_rules:
  - required_reviewers:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
  - wait_timer:
      wait_time: 5
  - deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false

environment_variables:
  NODE_ENV: production
  PUBLIC_SITE_URL: https://harmonia.jules.com
