name: staging
url: https://staging.harmonia.jules.com

protection_rules:
  - required_reviewers:
      required_approving_review_count: 0
      dismiss_stale_reviews: false
      require_code_owner_reviews: false
  - wait_timer:
      wait_time: 2
  - deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true

environment_variables:
  NODE_ENV: staging
  PUBLIC_SITE_URL: https://staging.harmonia.jules.com
